// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'api key',
    appId: '1:506199705329:web:2ac8023fd48ca01fd2cb50',
    messagingSenderId: '506199705329',
    projectId: 'farmassistor',
    authDomain: 'farmassistor.firebaseapp.com',
    storageBucket: 'farmassistor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPQAeCBmiiM4u9D6WYyrRERhVqb9dc8c',
    appId: '1:506199705329:android:911723d4651b4a8bd2cb50',
    messagingSenderId: '506199705329',
    projectId: 'farmassistor',
    storageBucket: 'farmassistor.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU7ejJbl_aCI4YOJSW1MOG-7eq_uKJAB8',
    appId: '1:506199705329:web:90a79b6b1f9fad49d2cb50',
    messagingSenderId: '506199705329',
    projectId: 'farmassistor',
    authDomain: 'farmassistor.firebaseapp.com',
    storageBucket: 'farmassistor.appspot.com',
  );
}
